version: 2
jobs:
  static:
    working_directory: ~/nextcloud-snap
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout

      - run:
         # Run the static tests
         command: |
           apt-get update -qq
           apt-get install -qq shellcheck
           ./tests/run-tests.sh static

  unit:
    working_directory: ~/nextcloud-snap
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout

      - run:
         # Run the unit tests
         command: |
           apt-get update -qq
           apt-get install -qq curl git
           ./tests/run-tests.sh unit

  integration:
    working_directory: ~/nextcloud-snap
    machine:
      image: ubuntu-1604:202004-01
    steps:
     - checkout

     - run:
         # Build the docker image necessary to build this snap
         command: |
           docker build -t nextcloud_builder .circleci/

     - run:
         # Build the snap
         command: |
           docker run -v $(pwd):$(pwd) \
                      -t nextcloud_builder \
                      sh -c "cd $(pwd) && apt update -qq && snapcraft"

     - run:
         # Install and run the review tools on the resulting snap
         command: |
           sudo apt-get update -qq
           sudo apt-get install -qq snapd
           sudo snap install review-tools
           sudo /snap/bin/review-tools.snap-review *.snap

     - run:
         # Install the snap and create an admin user
         command: |
           sudo snap install *.snap --dangerous

     - run:
         # Run the integration tests
         command: ./.circleci/runtests.sh

  test-daily-master:
    working_directory: ~/nextcloud-snap
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout

      - run:
          # Install the snap and create an admin user
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq snapd
            sudo snap install --edge nextcloud

      - run:
          # Run the tests
          command: ./.circleci/runtests.sh

  test-daily-v19:
    working_directory: ~/nextcloud-snap
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout

      - run:
          # Install the snap and create an admin user
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq snapd
            sudo snap install nextcloud --channel=19/edge

      - run:
          # Run the tests
          command: ./.circleci/runtests.sh

  test-daily-v20:
    working_directory: ~/nextcloud-snap
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout

      - run:
          # Install the snap and create an admin user
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq snapd
            sudo snap install nextcloud --channel=20/edge

      - run:
          # Run the tests
          command: ./.circleci/runtests.sh

  test-daily-v21:
    working_directory: ~/nextcloud-snap
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout

      - run:
          # Install the snap and create an admin user
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq snapd
            sudo snap install nextcloud --channel=21/edge

      - run:
          # Run the tests
          command: ./.circleci/runtests.sh

workflows:
  version: 2
  commit:
    jobs: [static, unit, integration]

  daily-master:
    triggers:
      - schedule:
          # 0700 UTC == 0000 PSC
          cron: "0 7 * * *"
          filters:
            branches:
              only: develop

    jobs: [test-daily-master]

  daily-v19:
    triggers:
      - schedule:
          # 0700 UTC == 0000 PSC
          cron: "0 7 * * *"
          filters:
            branches:
              only: develop

    jobs: [test-daily-v19]

  daily-v20:
    triggers:
      - schedule:
          # 0700 UTC == 0000 PSC
          cron: "0 7 * * *"
          filters:
            branches:
              only: develop

    jobs: [test-daily-v20]

  daily-v21:
    triggers:
      - schedule:
          # 0700 UTC == 0000 PSC
          cron: "0 7 * * *"
          filters:
            branches:
              only: develop

    jobs: [test-daily-v21]
