version: 2
jobs:
  build:
    working_directory: ~/nextcloud-snap
    machine: true
    steps:
     - checkout

     - run:
         # Build the snap
         command: |
           sudo apt update
           sudo apt install -y snapd
           docker run -v $(pwd):$(pwd) -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8 -t ubuntu:xenial sh -c "apt update -qq && apt install snapcraft -y && cd $(pwd) && snapcraft"

     - run:
         # Install the snap and create an admin user
         command: |
           sudo snap install *.snap --dangerous
           sudo nextcloud.manual-install admin admin

     - run:
         # Run the tests
         command: ./.circleci/runtests.sh

  test-daily-master:
    working_directory: ~/nextcloud-snap
    machine: true
    steps:
      - checkout

      - run:
          # Install the snap and create an admin user
          command: |
            sudo apt update
            sudo apt install -y snapd
            sudo snap install --edge nextcloud
            sudo nextcloud.manual-install admin admin

      - run:
          # Run the tests
          command: ./.circleci/runtests.sh

  test-daily-v11:
    working_directory: ~/nextcloud-snap
    machine: true
    steps:
      - checkout

      - run:
          # Install the snap and create an admin user
          command: |
            sudo apt update
            sudo apt install -y snapd
            sudo snap install nextcloud --channel=11/edge
            sudo nextcloud.manual-install admin admin

      - run:
          # Run the tests
          command: ./.circleci/runtests.sh

  test-daily-v12:
    working_directory: ~/nextcloud-snap
    machine: true
    steps:
      - checkout

      - run:
          # Install the snap and create an admin user
          command: |
            sudo apt update
            sudo apt install -y snapd
            sudo snap install nextcloud --channel=12/edge
            sudo nextcloud.manual-install admin admin

      - run:
          # Run the tests
          command: ./.circleci/runtests.sh

  test-daily-v13:
    working_directory: ~/nextcloud-snap
    machine: true
    steps:
      - checkout

      - run:
          # Install the snap and create an admin user
          command: |
            sudo apt update
            sudo apt install -y snapd
            sudo snap install nextcloud --channel=13/edge
            sudo nextcloud.manual-install admin admin

      - run:
          # Run the tests
          command: ./.circleci/runtests.sh

workflows:
  version: 2
  commit:
    jobs: [build]

  daily-master:
    triggers:
      - schedule:
          # 0700 UTC == 0000 PSC
          cron: "0 7 * * *"
          filters:
            branches:
              only: develop

    jobs: [test-daily-master]

  daily-v11:
    triggers:
      - schedule:
          # 0700 UTC == 0000 PSC
          cron: "0 7 * * *"
          filters:
            branches:
              only: develop

    jobs: [test-daily-v11]

  daily-v12:
    triggers:
      - schedule:
          # 0700 UTC == 0000 PSC
          cron: "0 7 * * *"
          filters:
            branches:
              only: develop

    jobs: [test-daily-v12]

  daily-v13:
    triggers:
      - schedule:
          # 0700 UTC == 0000 PSC
          cron: "0 7 * * *"
          filters:
            branches:
              only: develop

    jobs: [test-daily-v13]
